// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiService.Infrastructure;

namespace WebApiService.Infrastructure.Migrations
{
    [DbContext(typeof(EmployeesDBContext))]
    partial class EmployeesDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("WebApiService.Contracts.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            FirstName = "Mangesh",
                            LastName = "G"
                        },
                        new
                        {
                            EmployeeId = 2,
                            FirstName = "Ramnath",
                            LastName = "Bodke"
                        },
                        new
                        {
                            EmployeeId = 3,
                            FirstName = "Suraj",
                            LastName = "G"
                        },
                        new
                        {
                            EmployeeId = 4,
                            FirstName = "Jaffar",
                            LastName = "K"
                        });
                });

            modelBuilder.Entity("WebApiService.Contracts.Models.EmployeeData", b =>
                {
                    b.Property<int>("EmployeeDataId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<int>("EmployeeId");

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<string>("Phone");

                    b.HasKey("EmployeeDataId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("EmployeesData");

                    b.HasData(
                        new
                        {
                            EmployeeDataId = 1,
                            Email = "Mangesh.g@outlook.com",
                            EmployeeId = 1,
                            Gender = "1",
                            Phone = "123"
                        },
                        new
                        {
                            EmployeeDataId = 2,
                            Email = "Ramnagh.g@outlook.com",
                            EmployeeId = 2,
                            Gender = "1",
                            Phone = "223"
                        },
                        new
                        {
                            EmployeeDataId = 3,
                            Email = "suraj.g@gmail.com",
                            EmployeeId = 3,
                            Gender = "1",
                            Phone = "323"
                        },
                        new
                        {
                            EmployeeDataId = 4,
                            Email = "Jaffar.g@outlook.com",
                            EmployeeId = 4,
                            Gender = "1",
                            Phone = "423"
                        });
                });

            modelBuilder.Entity("WebApiService.Contracts.Models.EmployeeData", b =>
                {
                    b.HasOne("WebApiService.Contracts.Models.Employee")
                        .WithOne("EmployeeData")
                        .HasForeignKey("WebApiService.Contracts.Models.EmployeeData", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
